StartupEvents.registry('item', event => {
    //铜钥匙
    event.create('key_copper')
        .displayName('铜钥匙')
        .maxStackSize(64);
    //铁钥匙
    event.create('key_iron')
        .displayName('铁钥匙')
        .maxStackSize(64);
    //金钥匙
    event.create('key_gold')
        .displayName('金钥匙')
        .maxStackSize(64);
    //钻石钥匙
    event.create('key_diamond')
        .displayName('钻石钥匙')
        .maxStackSize(64);
    //下届合金钥匙
    event.create('key_netherite')
        .displayName('下界合金钥匙')
        .maxStackSize(64);
    //绿宝石钥匙
    event.create('key_emerald')
        .displayName('绿宝石钥匙')
        .maxStackSize(64);
    //后续按照这种格式添加钥匙之类的物品!!!
});
